name: Tests
on:
  push:
    branches: [ master, '[0-9]+.[0-9]+.[0-9]+', '[0-9]+.[0-9]+.[0-9]+-[A-Za-z0-9]+' ]
  pull_request:
    branches: [ master, '[0-9]+.[0-9]+.[0-9]+', '[0-9]+.[0-9]+.[0-9]+-[A-Za-z0-9]+' ]
# runs every monday at 9 am
  schedule:
    - cron: "0 9 * * 1"
  workflow_dispatch: null

jobs:
  code-samples:
    name: Test code samples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Generate harness
        working-directory: ./cookbook/tests
        run: ./generate.sh
      - name: Test code samples
        working-directory: ./cookbook/tests
        run: cargo test